// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQVPOsT14ycwsPnAboEN1oT0ctUDZ80A',
    appId: '1:251817339784:web:df5400ed26bf0c3474283d',
    messagingSenderId: '251817339784',
    projectId: 'planit-3e80d',
    authDomain: 'planit-3e80d.firebaseapp.com',
    storageBucket: 'planit-3e80d.firebasestorage.app',
    measurementId: 'G-NEM9V0W10F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaoUUB1yKZfrt5XRoVFdFXrnV-WW7WH9w',
    appId: '1:251817339784:android:175408bc14e8549b74283d',
    messagingSenderId: '251817339784',
    projectId: 'planit-3e80d',
    storageBucket: 'planit-3e80d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJO2njVL5YKC5EPJb7B2lnkLFXmqgC0sk',
    appId: '1:251817339784:ios:5bcd57767208987574283d',
    messagingSenderId: '251817339784',
    projectId: 'planit-3e80d',
    storageBucket: 'planit-3e80d.firebasestorage.app',
    iosBundleId: 'com.example.planIt',
  );
}
